name: hackingAndcoffee
favicon: null
layout_spectrum: 0.004776878748089075
typography_spectrum: 0.82509
title: "Welcome to my collection of clutter.  I'm in the process of migrating a bunch of stuff so figured, why not let the Grid throw it all into one bucket. Feel free to leave comments or reach out with any questions!"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.0241625071503222
  lightness: 0.46186408470384777
  saturation: 0.4470987895037979
  rhythmicContrast: 0.9464768145699054
purpose: []
